# Enhanced reporting with more detail and formatting

#' Comprehensive Health Report
#'
#' @description Creates a comprehensive report with specific treatment instructions
#'
#' @param results List. Results from checktor()
#' @param file Character. Output file path (optional)
#' @param format Character. Report format: "markdown", "html", or "text"
#'
#' @return Character vector with report content
#'
#' @export
health_report <- function(results, file = NULL, format = "markdown") {
  if (!inherits(results, "checktor_results")) {
    cli::cli_abort("Input must be a checktor_results object")
  }

  if (format == "markdown") {
    report <- generate_markdown_report(results)
  } else if (format == "html") {
    report <- generate_html_report(results)
  } else {
    report <- generate_text_report(results)
  }

  if (!is.null(file)) {
    writeLines(report, file)
    cli::cli_alert_success("Health report written to: {.path {file}}")
  }

  return(report)
}

generate_markdown_report <- function(results) {
  report <- c(
    "# Package Doctor - Health Report",
    "",
    paste("**Patient:** `", results$metadata$package_path, "`", sep = ""),
    paste("**Examination Date:** ", results$metadata$diagnosis_time),
    paste("**Doctor Version:** ", results$metadata$checktor_version),
    "",
    "## Executive Summary",
    ""
  )

  total_issues <- results$metadata$total_issues
  if (total_issues == 0) {
    report <- c(report,
                "**CLEAN BILL OF HEALTH** - Your package appears ready for CRAN submission.",
                "",
                "### Next Steps",
                "1. Run `R CMD check` or `devtools::check()` for standard checks",
                "2. Review the [CRAN submission checklist](https://cran.r-project.org/web/packages/submission_checklist.html)",
                "3. Submit to CRAN with confidence!"
    )
  } else {
    report <- c(report,
                paste("**REQUIRES TREATMENT:** ", total_issues, " issue(s) found that should be addressed before CRAN submission."),
                ""
    )

    # Add detailed sections for each category with issues
    categories <- c("code_issues", "description_issues", "documentation_issues", "general_issues")

    for (category in categories) {
      if (category %in% names(results)) {
        cat_results <- results[[category]]
        if ("passed" %in% names(cat_results)) {
          failed_checks <- names(cat_results$passed)[!cat_results$passed]
          if (length(failed_checks) > 0) {
            cat_name <- gsub("_", " ", tools::toTitleCase(category))
            report <- c(report, paste("## ", cat_name), "")

            for (check in failed_checks) {
              check_result <- cat_results[[check]]
              if (is.list(check_result) && "issues" %in% names(check_result)) {
                report <- c(report, paste("### ", gsub("_", " ", tools::toTitleCase(check))))

                # Add specific treatment instructions based on check type
                treatment_instructions <- get_treatment_instructions(check, check_result)
                if (!is.null(treatment_instructions)) {
                  report <- c(report, "", "**Treatment:**", treatment_instructions, "")
                }

                if (length(check_result$issues) > 0) {
                  report <- c(report, "**Affected Areas:**")
                  for (issue in utils::head(check_result$issues, 10)) {
                    report <- c(report, paste("- `", issue, "`", sep = ""))
                  }
                  if (length(check_result$issues) > 10) {
                    report <- c(report, paste("- ... and", length(check_result$issues) - 10, "more"))
                  }
                  report <- c(report, "")
                }
              }
            }
          }
        }
      }
    }
  }

  report <- c(report,
              "",
              "---",
              "*Report generated by [checktor - The Package Doctor](https://github.com/your-username/checktor)*"
  )

  return(report)
}

get_treatment_instructions <- function(check_name, check_result) {
  instructions <- switch(check_name,
                         "tf_usage" = c(
                           "Replace all instances of `T` with `TRUE` and `F` with `FALSE`.",
                           "```r",
                           "# Before treatment",
                           "result <- T",
                           "",
                           "# After treatment",
                           "result <- TRUE",
                           "```"
                         ),
                         "seed_setting" = c(
                           "Add a `seed` parameter to functions that set seeds:",
                           "```r",
                           "# Before treatment",
                           "my_function <- function(data) {",
                           "  set.seed(123)",
                           "  # ...",
                           "}",
                           "",
                           "# After treatment",
                           "my_function <- function(data, seed = NULL) {",
                           "  if (!is.null(seed)) set.seed(seed)",
                           "  # ...",
                           "}",
                           "```"
                         ),
                         "print_cat_usage" = c(
                           "Replace `print()`/`cat()` with `message()` or add verbose parameter:",
                           "```r",
                           "# Before treatment",
                           "print('Processing...')",
                           "",
                           "# After treatment - Option 1",
                           "message('Processing...')",
                           "",
                           "# After treatment - Option 2",
                           "if (verbose) cat('Processing...\\n')",
                           "```"
                         ),
                         NULL  # Default case
  )

  return(instructions)
}

generate_text_report <- function(results) {
  # Simple text version of the report
  report <- c(
    "Package Doctor - Health Report",
    paste("Generated on:", results$metadata$diagnosis_time),
    paste("Patient:", results$metadata$package_path),
    "",
    "Summary:",
    paste("Total Issues:", results$metadata$total_issues)
  )

  if (results$metadata$total_issues == 0) {
    report <- c(report, "", "Clean bill of health! Package appears ready for CRAN.")
  } else {
    report <- c(report, "", "Issues found - see detailed output from checktor() for treatments.")
  }

  return(report)
}

generate_html_report <- function(results) {
  # HTML version with basic styling
  html <- c(
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    "<title>Package Doctor - Health Report</title>",
    "<style>",
    "body { font-family: Arial, sans-serif; margin: 40px; }",
    ".header { color: #2c3e50; border-bottom: 2px solid #3498db; }",
    ".summary { background: #ecf0f1; padding: 15px; border-radius: 5px; }",
    ".issue { color: #e74c3c; }",
    ".success { color: #27ae60; }",
    "</style>",
    "</head>",
    "<body>",
    "<h1 class='header'>Package Doctor - Health Report</h1>",
    paste("<p><strong>Patient:</strong>", results$metadata$package_path, "</p>"),
    paste("<p><strong>Examination Date:</strong>", results$metadata$diagnosis_time, "</p>"),
    "<div class='summary'>",
    paste("<h2>Diagnosis:", results$metadata$total_issues, "issue(s) found</h2>")
  )

  if (results$metadata$total_issues == 0) {
    html <- c(html, "<p class='success'>Clean bill of health!</p>")
  } else {
    html <- c(html, "<p class='issue'>Treatment required - see checktor() output for details.</p>")
  }

  html <- c(html, "</div>", "</body>", "</html>")

  return(html)
}

# Helper functions for better error messages
validate_package_directory <- function(path) {
  if (!dir.exists(path)) {
    cli::cli_abort("Directory {.path {path}} does not exist")
  }

  if (!file.exists(file.path(path, "DESCRIPTION"))) {
    cli::cli_abort("No DESCRIPTION file found in {.path {path}}. Is this an R package directory?")
  }

  return(TRUE)
}
